"""replace stocks with stock_master reference, add index_price table

Revision ID: 7686b0fc0723
Revises: 7c9599644d36
Create Date: 2026-08-05 12:02:03.249524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7686b0fc0723'
down_revision: Union[str, Sequence[str], None] = '7c9599644d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # py_index_prices 생성, FK 제약 2개 제거는 이전 시도(부분 실패)에서 이미 완료됨
    op.drop_table('stocks')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('price_history_ibfk_1'), 'price_history', 'stocks', ['ticker'], ['ticker'])
    op.create_foreign_key(op.f('backtest_runs_ibfk_2'), 'backtest_runs', 'stocks', ['ticker'], ['ticker'])
    op.create_table('stocks',
    sa.Column('ticker', mysql.VARCHAR(collation='utf8mb4_general_ci', length=10), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('market', mysql.VARCHAR(collation='utf8mb4_general_ci', length=10), nullable=False),
    sa.PrimaryKeyConstraint('ticker'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=False)
    op.drop_table('py_index_prices')
    # ### end Alembic commands ###
