"""add backtest and live trading tables

Revision ID: 7c9599644d36
Revises: 6563188213dd
Create Date: 2026-08-04 10:35:37.837215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7c9599644d36'
down_revision: Union[str, Sequence[str], None] = '6563188213dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=True),
    sa.Column('kis_order_no', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('filled_qty', sa.Integer(), nullable=True),
    sa.Column('filled_price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_orders_id'), 'live_orders', ['id'], unique=False)
    op.create_table('py_user_kis_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kis_app_key_encrypted', sa.String(length=500), nullable=False),
    sa.Column('kis_app_secret_encrypted', sa.String(length=500), nullable=False),
    sa.Column('kis_account_no', sa.String(length=20), nullable=False),
    sa.Column('kis_account_product_cd', sa.String(length=5), nullable=True),
    sa.Column('is_mock', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_py_user_kis_credentials_user_id'), 'py_user_kis_credentials', ['user_id'], unique=True)
    op.create_table('py_user_strategy_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('buy_threshold', sa.Float(), nullable=True),
    sa.Column('sell_threshold', sa.Float(), nullable=True),
    sa.Column('stop_loss_pct', sa.Float(), nullable=True),
    sa.Column('take_profit_pct', sa.Float(), nullable=True),
    sa.Column('max_positions', sa.Integer(), nullable=True),
    sa.Column('position_size_pct', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_py_user_strategy_settings_user_id'), 'py_user_strategy_settings', ['user_id'], unique=True)
    op.create_table('stocks',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_ticker_date')
    )
    op.create_index(op.f('ix_price_history_date'), 'price_history', ['date'], unique=False)
    op.create_index(op.f('ix_price_history_ticker'), 'price_history', ['ticker'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('mdd', sa.Float(), nullable=False),
    sa.Column('sharpe_ratio', sa.Float(), nullable=False),
    sa.Column('benchmark_return', sa.Float(), nullable=True),
    sa.Column('buy_hold_return', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_run_id'), 'trades', ['run_id'], unique=False)
    op.add_column('py_momentum_rank', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('py_momentum_rank', sa.Column('ticker', sa.String(length=10), nullable=False))
    op.add_column('py_momentum_rank', sa.Column('close', sa.Float(), nullable=True))
    op.add_column('py_momentum_rank', sa.Column('close_n_days_ago', sa.Float(), nullable=True))
    op.add_column('py_momentum_rank', sa.Column('momentum_pct', sa.Float(), nullable=True))
    op.add_column('py_momentum_rank', sa.Column('rank_pct', sa.Float(), nullable=True))
    op.drop_column('py_momentum_rank', 'stock_code')
    op.drop_column('py_momentum_rank', 'base_date')
    op.drop_column('py_momentum_rank', 'rank_no')
    op.drop_column('py_momentum_rank', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('py_momentum_rank', sa.Column('score', mysql.DECIMAL(precision=12, scale=4), nullable=True))
    op.add_column('py_momentum_rank', sa.Column('rank_no', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('py_momentum_rank', sa.Column('base_date', sa.DATE(), nullable=False))
    op.add_column('py_momentum_rank', sa.Column('stock_code', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('py_momentum_rank', 'rank_pct')
    op.drop_column('py_momentum_rank', 'momentum_pct')
    op.drop_column('py_momentum_rank', 'close_n_days_ago')
    op.drop_column('py_momentum_rank', 'close')
    op.drop_column('py_momentum_rank', 'ticker')
    op.drop_column('py_momentum_rank', 'date')
    op.drop_index(op.f('ix_trades_run_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_price_history_ticker'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_date'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_table('backtest_runs')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_py_user_strategy_settings_user_id'), table_name='py_user_strategy_settings')
    op.drop_table('py_user_strategy_settings')
    op.drop_index(op.f('ix_py_user_kis_credentials_user_id'), table_name='py_user_kis_credentials')
    op.drop_table('py_user_kis_credentials')
    op.drop_index(op.f('ix_live_orders_id'), table_name='live_orders')
    op.drop_table('live_orders')
    # ### end Alembic commands ###
