"""remove py_index_prices, use index_candles_1d instead

Revision ID: afc1394c50b6
Revises: 09c7e698eed4
Create Date: 2026-08-12 10:13:13.423779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'afc1394c50b6'
down_revision: Union[str, Sequence[str], None] = '09c7e698eed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('py_index_prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('py_index_prices',
    sa.Column('index_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=10), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('open', mysql.FLOAT(), nullable=False),
    sa.Column('high', mysql.FLOAT(), nullable=False),
    sa.Column('low', mysql.FLOAT(), nullable=False),
    sa.Column('close', mysql.FLOAT(), nullable=False),
    sa.Column('volume', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('index_code', 'date'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
