"""remove price_history, use stock_candles_1d instead

Revision ID: b7d623317aa8
Revises: 7686b0fc0723
Create Date: 2026-08-10 11:01:08.792828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b7d623317aa8'
down_revision: Union[str, Sequence[str], None] = '7686b0fc0723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_date'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_ticker'), table_name='price_history')
    op.drop_index(op.f('uq_ticker_date'), table_name='price_history')
    op.drop_table('price_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker', mysql.VARCHAR(collation='utf8mb4_general_ci', length=10), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('open', mysql.FLOAT(), nullable=False),
    sa.Column('high', mysql.FLOAT(), nullable=False),
    sa.Column('low', mysql.FLOAT(), nullable=False),
    sa.Column('close', mysql.FLOAT(), nullable=False),
    sa.Column('volume', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_ticker_date'), 'price_history', ['ticker', 'date'], unique=True)
    op.create_index(op.f('ix_price_history_ticker'), 'price_history', ['ticker'], unique=False)
    op.create_index(op.f('ix_price_history_date'), 'price_history', ['date'], unique=False)
    # ### end Alembic commands ###
