"""add reason column to live_orders

Revision ID: e014d15f6f12
Revises: 429221a3abc4
Create Date: 2026-07-15 11:54:00.815204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e014d15f6f12'
down_revision: Union[str, Sequence[str], None] = '429221a3abc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_orders', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_orders', 'reason')
    # ### end Alembic commands ###
